### PR TITLE
basic windows files \r check for directive names

### PR DESCRIPTION
**Pull request by 0x546F6D**
Could not compile zig-zag-zoe on windows because of @compileError(directiveNotFound) due to \r\n used by windows file.
This workaround might not be the most sophisticated way to handle this problem.

### CODE REVIEW

**Comment by zigster64** [comment]
Nice work, thanks for posting this

will get it merged shortly no probs

**Comment by zigster64** [comment]
… be interested in seeing how you go with getting the game running on windows too

the game itself is a bit lame, but it’s a good excuse to study SSE usage on htmx ;)

**Comment by 0x546F6D** [comment]
I took a few shortcuts to make it run on windows :)
such as:
``` zig
    if (builtin.os.tag != .windows) {
        const env_port = std.posix.getenv("PORT");
        // ...
        args = std.process.args();
    } else {
        args = try std.process.argsWithAllocator(allocator);
    }
```
and
``` zig
    const hostname = if (builtin.os.tag == .windows) "localhost" else {
        var hostBuffer: [std.posix.HOST_NAME_MAX]u8 = undefined;
        try std.posix.gethostname(&hostBuffer);
    };
```

and I then followed [http.zig migration guide](https://github.com/karlseguin/http.zig/wiki/Migration) to udpate main.zig:
``` zig
    var server = try httpz.Server(*Game).init(allocator, .{
        .address = "0.0.0.0",
        .port = port,
    }, &game);
    // server.notFound(notFound);
    // server.errorHandler(errorHandler);
    // server.dispatcher(Game.logger);

    var router = server.router(.{});
    router.get("/", indexHTML, .{});
    router.get("/index.html", indexHTML, .{});
    // router.get("/htmx.min.js", htmx);
    router.get("/styles.css", stylesCSS, .{});
    router.get("/favicon.ico", favicon, .{});
```
and game.zig:
``` zig
pub fn notFound(self: *Self, req: *httpz.Request, res: *httpz.Response) !void {
    // std.log.info("Bad client {} tried for a thing not found - ban them", .{req.address.in.sa.addr});
    self.logExtra(req, "(404 Not Found)");
    res.status = 404;
    res.body = "File not found";
}

// note that the error handler return `void` and not `!void`
pub fn uncaughtError(self: *Self, req: *httpz.Request, res: *httpz.Response, err: anyerror) void {
    self.logExtra(req, "(500 Error)");
    res.status = 500;
    res.body = "Error";
    std.log.err("Error {} on request {s}", .{ err, req.url.raw });
}

pub fn dispatch(self: *Self, action: httpz.Action(*Self), req: *httpz.Request, res: *httpz.Response) !void {
    // comment this debug out if you want to log the entry to each function - maybe for debugging some handle that hangs
    // std.log.debug("[{}:{s}] {s} {s} START ..", .{ std.time.timestamp(), @tagName(self.state), @tagName(req.method), req.url.raw });
    const t1 = std.time.microTimestamp();
    defer self.log(req, std.time.microTimestamp() - t1);
    return action(self, req, res);
}

/// addRoutes sets up the routes and handlers used in this game object
pub fn addRoutes(self: *Self, router: anytype) void {
    _ = self;
    router.get("/events", Self.events, .{}); // SSE event stream of game state changes
    router.get("/app", Self.app, .{}); // Get the app contents, which depends on the current user + game state
    router.get("/header", Self.header, .{}); // Get the header fragment that describes the game state
    router.post("/setup", Self.setup, .{}); // Process the setup for a new game
    router.post("/login/:player", Self.login, .{}); // login !
    router.post("/square/:x/:y", Self.square, .{}); // player clicks on a square
    router.post("/restart", Self.restart, .{});
    router.get("/images/zero-wing.jpg", Self.zeroWing, .{});

    router.get("/audio/your-turn.mp3", Self.yourTurnAudio, .{});
    router.get("/audio/zero-wing.mp3", Self.zeroWingAudio, .{});
    router.get("/audio/nuke.mp3", Self.nukeAudio, .{});
    router.get("/audio/victory.mp3", Self.victoryAudio, .{});
    router.get("/audio/lost.mp3", Self.lostAudio, .{});
}
```
I think that's pretty much all I had to do to, but it does not work consistently. I sometimes have to open 1 firefox, 1 chrome, then the private firefox, then the uncognito chrome, and do a bunch of refreshes to get 2 of them working to play against each other.

I used your zig-zag-zoe game to:
- learn about http.zig
- learn about [zig-webui](https://github.com/webui-dev/zig-webui) by turning it into an executable for windows.
- learn about htmx with http.zig, but then discovered [datastar](https://github.com/starfederation/datastar) (an htmx-like framework that relies heavily on SSE), so I used your project once again to learn about SSE with http.zig

All in all, thanks a lot :)

**Comment by zigster64** [comment]
Awesome, thanks

Yeah, there has been a few http.zig changes as 0.14 evolves ... I probably will revisit this project after 0.14 proper lands, and do some cleanup, and have a closer look at those reliability bugs. They dont happen all the time, but when they do, they are hard to debug

Interesting to hear that you could create an exe using zig-webui - I will have to have a look into that. Be wonderful if one day we could write apps using common enough webdev idioms, and just compile it for iOS / Android / Win / Linux / Mac ... and it just magically works

Datastar looks cool too - bit more holistic full stack than htmx by the looks. Glad to see that project growing well and getting some eyes on it. Another thing I will have to catch up on when time permits, hey

**Pull request merged**
